package com.learning.lowleveldesign.cricbuzz.model;

public enum StatType {
  RUNSPEROVER, WICKETS, TOTALRUNS, WICKETSPEROVER, MATCHESPLAYED, NOOFINNINGS, AVGRUNRATE, AVGRUNSPERMATCH, NOOFBALLSFACED;
}
